// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"context"
)

type Querier interface {
	ListColors(ctx context.Context) ([]Color, error)
	SetStatus(ctx context.Context, arg SetStatusParams) error
}

var _ Querier = (*Queries)(nil)
