// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"context"
)

type Querier interface {
	ContactWithID(ctx context.Context, id int64) (Contact, error)
	ListContacts(ctx context.Context) ([]Contact, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) error
}

var _ Querier = (*Queries)(nil)
